global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-job'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spring-api-gateway-monitoring-job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 4s
    static_configs:
      - targets: ['api-gateway:8181']
        labels:
          application: 'API-GATEWAY'